version: "3.5"
services:
  httpd:
    image: httpd:latest
    #ports:
    #  - "80:80"
    expose:
      - "80"
    volumes:
      - ./app:/app
      - ./conf:/usr/local/apache2/conf
      - ./logs/front:/logs

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vitemonreseau.rule=Host(`vitemonreseau.com`, `vitemonreseau.fr`,`www.vitemonreseau.com`, `www.vitemonreseau.fr`)"
      - "traefik.http.routers.vitemonreseau.tls.certresolver=le"
      - "traefik.http.routers.vitemonreseau.entrypoints=websecure, web"
    links:
      - php

    networks:
      - traeffik
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile

    volumes:
      - ./app:/app
    networks:
      - traeffik

networks:
  traeffik:
    external:
      name: traefik_webgateway
